### ISSUE TITLE
你好，请问有没有畅购的数据库？

### ISSUE THREAD

**Issue by 786744873** [imlty/all-changgou#1]
你好，请问有没有畅购的数据库？麻烦留个联系方式

**Comment by imlty** [comment]
https://www.laopaojava.com/ 上面有哦 谢谢。

**Comment by imlty** [comment]
> 你好，请问有没有畅购的数据库？麻烦留个联系方式

laopaojava.com  这上面有哈 谢谢。

**Comment by imlty** [comment]
laopaojava.com 这上面有哈 谢谢。
